language: go
go:
  - "1.x" # use the latest Go release

branches:
  only:
  - master

env:
  global:
    - GO111MODULE=on
    - GOLANGCI_LINT_VERSION=1.18.0

cache:
  directories:
    - $HOME/.cache/go-build
    - $GOPATH/pkg/mod

jobs:
  include:
    - name: lint
      env: CACHE_NAME=lint
      before_script:
        - |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh \
            | bash -s - -b $GOPATH/bin v${GOLANGCI_LINT_VERSION}
      install: skip
      script:
        - bash .github/assert-contributors.sh
        - bash .github/lint-disallowed-functions-in-library.sh
        - bash .github/lint-commit-message.sh
        - bash .github/lint-filename.sh
        - golangci-lint run ./...
    - name: test
      env: CACHE_NAME=test
      before_install:
        - go mod download
      install:
        - go build ./...
      script:
        - coverpkgs=$(go list ./... | grep -v examples | paste -s -d ',')
        - |
          go test \
            -coverpkg=${coverpkgs} -coverprofile=cover.out -covermode=atomic \
            -v -race ./...
      after_success:
        - travis_retry bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
